server:
  port: 9000
spring:
  application:
    name: aperture_gateway
  cloud:
    nacos:
      discovery:
        namespace: 119.3.186.94:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes[0]:
        id: aperture_acl
        uri: lb://aperture_acl
        predicates: Path=/*/acl/**




